git update at firsr
git test commit 29
updated
update test666
update test36

update merge branch test

git cherrypicktest from diff branch

merge conflict etst25235356
git conflict test
git amend changes

git merge confilce testsetset253636
git reset test commit 
reset comd

new branch testdd
git merge confilce testsetset253636test

new branch cherrpick merge conflict
git rebase branch 1 
git merge rebase conflict test

git cherrypicktest from diff branch
git rebasr tetaetwagaflkasdjfakjf
test git rebase take
git merge testt rebasing
git amend testte 5326 forgot to add
git commit test amm
git forgot add this commit as wll
git commit test
git last commit test